[project]
name = 'accordium'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.accordium]
path = 'contracts/accordium.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
